"""One-shot deploy command for OpenOps.

Provides a streamlined deployment flow that analyzes the project
and deploys to the specified platform with minimal interaction.
"""

import logging
import uuid
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from rich.live import Live
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.spinner import Spinner
from rich.table import Table

from openops.cli.main import app, show_error
from openops.cli.runtime import create_runtime
from openops.config import OPENOPS_ENV_FILE, get_config
from openops.credentials.platforms import (
    get_deployment_platform_ids,
    get_platform,
    get_platform_credential,
)
from openops.exceptions import CredentialError, OpenOpsError

logger = logging.getLogger(__name__)
console = Console()


def _prompt_for_credential(platform_id: str) -> str | None:
    """Prompt user for platform credential and save to env file.

    Args:
        platform_id: Platform identifier (e.g., "vercel")

    Returns:
        Credential value if provided, None if skipped
    """
    platform = get_platform(platform_id)
    if not platform:
        return None

    console.print()
    console.print(f"[yellow]No {platform.name} credentials configured.[/yellow]")
    console.print(f"[dim]Get your token at: {platform.help_url}[/dim]")
    console.print()

    token = Prompt.ask(
        f"Enter your {platform.name} token/API key (or press Enter to skip)",
        password=True,
        default="",
    )

    if not token.strip():
        return None

    token = token.strip()

    OPENOPS_ENV_FILE.parent.mkdir(parents=True, exist_ok=True)

    existing_vars: dict[str, str] = {}
    if OPENOPS_ENV_FILE.exists():
        with open(OPENOPS_ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    existing_vars[key.strip()] = value.strip()

    existing_vars[platform.env_var] = token

    with open(OPENOPS_ENV_FILE, "w") as f:
        f.write("# OpenOps Configuration\n")
        f.write("# Generated by 'openops init'\n\n")
        for key, value in sorted(existing_vars.items()):
            f.write(f"{key}={value}\n")

    console.print(f"[green]✓[/green] {platform.name} credential saved")
    logger.info(f"Saved {platform.name} credential to {OPENOPS_ENV_FILE}")

    return token


def _extract_response_content(result: dict) -> str:
    """Extract the assistant's response content from the result."""
    messages = result.get("messages", [])
    if not messages:
        return "No response received."

    last_message = messages[-1]

    if hasattr(last_message, "content"):
        return last_message.content
    elif isinstance(last_message, dict):
        return last_message.get("content", str(last_message))
    return str(last_message)


def _show_project_summary(project_path: Path) -> None:
    """Display a brief project summary."""
    console.print()
    console.print(f"[bold]Project:[/bold] {project_path}")

    indicators = []
    if (project_path / "package.json").exists():
        indicators.append("Node.js")
    if (project_path / "pyproject.toml").exists():
        indicators.append("Python")
    if (project_path / "next.config.js").exists() or (project_path / "next.config.mjs").exists():
        indicators.append("Next.js")
    if (project_path / "vercel.json").exists():
        indicators.append("Vercel config")
    if (project_path / "railway.json").exists() or (project_path / "railway.toml").exists():
        indicators.append("Railway config")

    if indicators:
        console.print(f"[bold]Detected:[/bold] {', '.join(indicators)}")
    console.print()


def _handle_deployment_approval(runtime, thread_id: str, platform: str) -> dict | None:
    """Handle deployment approval when agent triggers interrupt."""
    try:
        state = runtime.get_state(thread_id)

        if state and hasattr(state, "tasks"):
            for task in state.tasks or []:
                if task.get("interrupts"):
                    interrupt = task["interrupts"][0]

                    table = Table(title="Deployment Details", show_header=True)
                    table.add_column("Field", style="cyan")
                    table.add_column("Value", style="green")
                    table.add_row("Platform", platform)

                    if "args" in interrupt:
                        for key, value in interrupt["args"].items():
                            display_value = str(value)
                            if len(display_value) > 60:
                                display_value = display_value[:57] + "..."
                            table.add_row(key, display_value)

                    console.print(table)
                    console.print()

                    if Confirm.ask("[yellow]Proceed with deployment?[/yellow]", default=True):
                        return runtime.resume(thread_id, "approve")
                    else:
                        reason = Prompt.ask("[dim]Reason (optional)[/dim]", default="")
                        return runtime.resume(thread_id, "reject", message=reason)

        return None
    except Exception as e:
        logger.debug(f"Error checking for interrupt: {e}")
        return None


@app.command()
def deploy(
    project_path: Annotated[
        Path | None,
        typer.Argument(
            help="Path to the project directory. Defaults to current directory.",
        ),
    ] = None,
    platform: Annotated[
        str,
        typer.Option(
            "--platform",
            "-p",
            help="Deployment platform (vercel, railway, render).",
        ),
    ] = "vercel",
    dry_run: Annotated[
        bool,
        typer.Option(
            "--dry-run",
            "-n",
            help="Show what would be deployed without actually deploying.",
        ),
    ] = False,
    auto_approve: Annotated[
        bool,
        typer.Option(
            "--yes",
            "-y",
            help="Auto-approve deployment without confirmation.",
        ),
    ] = False,
    env_file: Annotated[
        Path | None,
        typer.Option(
            "--env-file",
            "-e",
            help="Path to .env file for environment variables.",
        ),
    ] = None,
) -> None:
    """Deploy the project to a cloud platform.

    Analyzes your project, generates necessary configuration files,
    and deploys to the specified platform.

    Examples:

        openops deploy                  # Deploy to default platform (Vercel)

        openops deploy --platform railway   # Deploy to Railway

        openops deploy --dry-run        # Show what would be deployed

        openops deploy --yes            # Deploy without confirmation
    """
    project_path = (project_path or Path.cwd()).resolve()

    if not project_path.exists():
        show_error(
            FileNotFoundError(f"Project path does not exist: {project_path}"),
            hint="Check the path and try again.",
        )
        raise typer.Exit(1)

    platform = platform.lower()
    valid_platforms = get_deployment_platform_ids()
    if platform not in valid_platforms:
        show_error(
            ValueError(f"Invalid platform: {platform}"),
            hint=f"Valid platforms: {', '.join(valid_platforms)}",
        )
        raise typer.Exit(1)

    config = get_config()

    if not config.validate_llm_credentials():
        show_error(
            CredentialError(f"No API key configured for {config.model_provider}"),
            hint="Run 'openops init' to configure your LLM provider",
        )
        raise typer.Exit(1)

    platform_token = get_platform_credential(platform, config)

    if not platform_token:
        platform_token = _prompt_for_credential(platform)

        if not platform_token:
            show_error(
                CredentialError(f"No credentials configured for {platform}"),
                hint=f"Run 'openops credentials add {platform}' to configure",
            )
            raise typer.Exit(1)

        config = get_config()

    console.print(
        Panel(
            f"[bold blue]OpenOps Deploy[/bold blue]\n"
            f"Platform: [cyan]{platform.title()}[/cyan]" + (" [yellow](dry run)[/yellow]" if dry_run else ""),
            border_style="blue",
        )
    )

    _show_project_summary(project_path)

    thread_id = str(uuid.uuid4())

    try:
        runtime = create_runtime(working_directory=project_path, config=config)
    except Exception as e:
        logger.exception("Failed to create runtime")
        show_error(e, hint="Check your configuration and try again.")
        raise typer.Exit(1) from e

    try:
        deploy_message = f"Deploy this project to {platform}."
        if dry_run:
            deploy_message = (
                f"Analyze this project and show me what would be needed to deploy to {platform}."
                "Do NOT actually deploy."
            )
        if env_file and env_file.exists():
            deploy_message += f" Use environment variables from {env_file}."

        with Live(
            Spinner("dots", text="Analyzing project...", style="blue"),
            refresh_per_second=10,
            transient=True,
        ):
            result = runtime.invoke(deploy_message, thread_id)

        content = _extract_response_content(result)
        console.print(Panel(content, title="Analysis", border_style="dim"))

        if dry_run:
            console.print()
            console.print("[yellow]Dry run complete. No deployment was made.[/yellow]")
            return

        if not auto_approve:
            approval_result = _handle_deployment_approval(runtime, thread_id, platform)
            if approval_result:
                content = _extract_response_content(approval_result)
                console.print(Panel(content, title="Deployment Result", border_style="green"))
            else:
                console.print()
                if not Confirm.ask("[yellow]Proceed with deployment?[/yellow]", default=True):
                    console.print("[dim]Deployment cancelled.[/dim]")
                    return

                with Live(
                    Spinner("dots", text="Deploying...", style="blue"),
                    refresh_per_second=10,
                    transient=True,
                ):
                    result = runtime.invoke("Yes, proceed with the deployment.", thread_id)

                content = _extract_response_content(result)
                console.print(Panel(content, title="Deployment Result", border_style="green"))
        else:
            approval_result = _handle_deployment_approval(runtime, thread_id, platform)
            if approval_result:
                content = _extract_response_content(approval_result)
                console.print(Panel(content, title="Deployment Result", border_style="green"))

    except OpenOpsError as e:
        show_error(e)
        raise typer.Exit(1) from e
    except Exception as e:
        logger.exception("Deployment failed")
        show_error(e, hint="Run with --debug for more details")
        raise typer.Exit(1) from e
    finally:
        runtime.close()


__all__ = ["deploy"]
