"""Initialization wizard for OpenOps.

Guides users through first-time setup: LLM provider selection,
API key configuration, and platform credential setup.
"""

import logging
import os
from typing import Annotated

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

from openops.cli.main import app
from openops.config import OPENOPS_ENV_FILE, get_config

logger = logging.getLogger(__name__)
console = Console()


def _write_env_file(env_vars: dict[str, str]) -> None:
    """Write environment variables to the OpenOps .env file."""
    OPENOPS_ENV_FILE.parent.mkdir(parents=True, exist_ok=True)

    existing_vars: dict[str, str] = {}
    if OPENOPS_ENV_FILE.exists():
        with open(OPENOPS_ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    existing_vars[key.strip()] = value.strip()

    existing_vars.update(env_vars)

    with open(OPENOPS_ENV_FILE, "w") as f:
        f.write("# OpenOps Configuration\n")
        f.write("# Generated by 'openops init'\n\n")
        for key, value in sorted(existing_vars.items()):
            f.write(f"{key}={value}\n")

    logger.info(f"Updated env file: {OPENOPS_ENV_FILE}")


def _test_llm_connection(provider: str, api_key: str) -> bool:
    """Test connection to the LLM provider."""
    console.print("[dim]Testing connection...[/dim]")

    try:
        if provider == "anthropic":
            from langchain_anthropic import ChatAnthropic

            llm = ChatAnthropic(model="claude-haiku-4-5", api_key=api_key, max_tokens=10)
            llm.invoke("Hi")
        elif provider == "openai":
            from langchain_openai import ChatOpenAI

            llm = ChatOpenAI(model="gpt-5.4-nano", api_key=api_key, max_tokens=10)
            llm.invoke("Hi")
        elif provider == "google":
            from langchain_google_genai import ChatGoogleGenerativeAI

            llm = ChatGoogleGenerativeAI(
                model="gemini-2.5-flash-lite",
                google_api_key=api_key,
                max_output_tokens=10,
            )
            llm.invoke("Hi")
        elif provider == "deepseek":
            from langchain_openai import ChatOpenAI

            llm = ChatOpenAI(
                model="deepseek-chat",
                api_key=api_key,
                base_url="https://api.deepseek.com",
                max_tokens=10,
            )
            llm.invoke("Hi")
        else:
            console.print(f"[yellow]Skipping connection test for {provider}[/yellow]")
            return True

        return True
    except Exception as e:
        logger.debug(f"Connection test failed: {e}")
        return False


PROVIDER_MODELS = {
    "anthropic": [
        ("claude-sonnet-4-6", "Claude Sonnet 4.6 (recommended)"),
        ("claude-opus-4-6", "Claude Opus 4.6 (most capable)"),
        ("claude-haiku-4-5", "Claude Haiku 4.5 (fast, cheap)"),
        ("claude-sonnet-4-5-20250929", "Claude Sonnet 4.5"),
        ("claude-opus-4-5-20251101", "Claude Opus 4.5"),
    ],
    "openai": [
        ("gpt-5.4", "GPT-5.4 (recommended)"),
        ("gpt-5.4-mini", "GPT-5.4 Mini (fast, balanced)"),
        ("gpt-5.4-nano", "GPT-5.4 Nano (cheapest)"),
        ("o3", "o3 (reasoning, legacy)"),
        ("o3-pro", "o3-pro (deep reasoning, legacy)"),
    ],
    "google": [
        ("gemini-2.5-flash", "Gemini 2.5 Flash (recommended)"),
        ("gemini-2.5-pro", "Gemini 2.5 Pro (complex tasks)"),
        ("gemini-2.5-flash-lite", "Gemini 2.5 Flash-Lite (cheapest)"),
        ("gemini-3-flash", "Gemini 3 Flash (preview)"),
        ("gemini-3.1-pro", "Gemini 3.1 Pro (preview, advanced)"),
    ],
    "deepseek": [
        ("deepseek-chat", "DeepSeek-V3.2 Chat (recommended)"),
        ("deepseek-reasoner", "DeepSeek-V3.2 Reasoner (thinking mode)"),
    ],
}


def _select_model(provider: str) -> str:
    """Let user select a model for the given provider.

    Args:
        provider: The LLM provider (anthropic, openai, google)

    Returns:
        Selected model name
    """
    models = PROVIDER_MODELS.get(provider, [])

    if not models:
        return Prompt.ask("Enter model name")

    console.print()
    console.print(f"[bold]Available {provider.title()} models:[/bold]")

    for i, (model_id, description) in enumerate(models, 1):
        console.print(f"  {i}. {description} [dim]({model_id})[/dim]")
    console.print(f"  {len(models) + 1}. Custom (enter model name)")
    console.print()

    choices = [str(i) for i in range(1, len(models) + 2)]
    selection = Prompt.ask(
        "Select model",
        choices=choices,
        default="1",
    )

    idx = int(selection) - 1
    if idx < len(models):
        model_name = models[idx][0]
        console.print(f"[green]✓[/green] Selected: {model_name}")
        return model_name
    else:
        custom_model = Prompt.ask("Enter custom model name")
        return custom_model.strip()


def _setup_llm_provider() -> tuple[str, str, str] | None:
    """Guide user through LLM provider setup.

    Returns tuple of (provider, model, api_key) or None if skipped.
    """
    console.print()
    console.print("[bold]Step 1: LLM Provider[/bold]")
    console.print()

    provider = Prompt.ask(
        "Choose your LLM provider",
        choices=["anthropic", "openai", "google", "deepseek", "skip"],
        default="anthropic",
    )

    if provider == "skip":
        console.print("[dim]Skipping LLM setup. You can set this later via environment variables.[/dim]")
        return None

    model_name = _select_model(provider)

    env_var_names = {
        "anthropic": "ANTHROPIC_API_KEY",
        "openai": "OPENAI_API_KEY",
        "google": "GOOGLE_API_KEY",
        "deepseek": "DEEPSEEK_API_KEY",
    }

    env_var = env_var_names[provider]
    existing_key = os.environ.get(env_var)

    if existing_key:
        console.print(f"[green]✓[/green] Found existing {env_var}")
        if not Confirm.ask("Use existing key?", default=True):
            existing_key = None

    if not existing_key:
        api_key = Prompt.ask(f"Enter your {provider.title()} API key", password=True)

        if _test_llm_connection(provider, api_key):
            console.print("[green]✓[/green] Connection successful!")
        else:
            console.print("[red]✗[/red] Connection failed. Check your API key.")
            if not Confirm.ask("Save anyway?", default=False):
                return None
    else:
        api_key = existing_key

    return provider, model_name, api_key


def _show_summary(env_vars: dict[str, str]) -> None:
    """Show configuration summary."""
    console.print()
    console.print(Panel("[bold green]Setup Complete![/bold green]", style="green"))
    console.print()

    config = get_config()

    console.print("[bold]Configuration saved to:[/bold]")
    console.print(f"  {OPENOPS_ENV_FILE}")
    console.print()

    console.print("[bold]Data directory:[/bold]")
    console.print(f"  {config.data_dir}")
    console.print()

    if env_vars:
        console.print("[bold]Configured:[/bold]")
        for key in sorted(env_vars.keys()):
            masked = key.replace("_API_KEY", "").replace("_TOKEN", "").replace("OPENOPS_", "")
            console.print(f"  [green]✓[/green] {masked}")

    console.print()
    console.print("[bold]Next steps:[/bold]")
    console.print("  1. Run [cyan]openops chat[/cyan] to start chatting with OpenOps")
    console.print("  2. Run [cyan]openops doctor[/cyan] to verify your setup")
    console.print()
    console.print("[dim]Platform credentials (Vercel, Railway, Render) will be requested when you deploy.[/dim]")
    console.print("[dim]Or add them anytime with: [cyan]openops credentials add <platform>[/cyan][/dim]")


@app.command("init")
def init_cmd(
    provider: Annotated[
        str | None,
        typer.Option(
            "--provider",
            "-p",
            help="LLM provider to use (anthropic, openai, google, deepseek).",
        ),
    ] = None,
    non_interactive: Annotated[
        bool,
        typer.Option(
            "--non-interactive",
            "-y",
            help="Non-interactive mode (use defaults).",
        ),
    ] = False,
) -> None:
    """Initialize OpenOps configuration.

    Sets up your LLM provider and model. Platform credentials (Vercel, Railway,
    Render) are configured later when you deploy, keeping init fast and simple.

    Examples:

        openops init                        # Interactive setup

        openops init --provider anthropic   # Quick setup with provider

        openops init -y                     # Non-interactive with defaults
    """
    console.print(
        Panel(
            "[bold blue]Welcome to OpenOps![/bold blue]\n\n" "Let's set up your environment.",
            title="Setup Wizard",
            border_style="blue",
        )
    )

    env_vars: dict[str, str] = {}

    if non_interactive:
        if provider:
            env_vars["OPENOPS_MODEL_PROVIDER"] = provider
            default_models = {
                "anthropic": "claude-sonnet-4-6",
                "openai": "gpt-5.4",
                "google": "gemini-2.5-flash",
                "deepseek": "deepseek-chat",
            }
            if provider in default_models:
                env_vars["OPENOPS_MODEL_NAME"] = default_models[provider]
        console.print("[dim]Non-interactive mode: using defaults[/dim]")
    else:
        if provider:
            env_var_names = {
                "anthropic": "ANTHROPIC_API_KEY",
                "openai": "OPENAI_API_KEY",
                "google": "GOOGLE_API_KEY",
                "deepseek": "DEEPSEEK_API_KEY",
            }
            if provider in env_var_names:
                env_vars["OPENOPS_MODEL_PROVIDER"] = provider

                model_name = _select_model(provider)
                env_vars["OPENOPS_MODEL_NAME"] = model_name

                existing_key = os.environ.get(env_var_names[provider])
                if not existing_key:
                    api_key = Prompt.ask(f"Enter your {provider.title()} API key", password=True)
                    env_vars[env_var_names[provider]] = api_key
        else:
            llm_result = _setup_llm_provider()
            if llm_result:
                llm_provider, model_name, api_key = llm_result
                env_var_names = {
                    "anthropic": "ANTHROPIC_API_KEY",
                    "openai": "OPENAI_API_KEY",
                    "google": "GOOGLE_API_KEY",
                    "deepseek": "DEEPSEEK_API_KEY",
                }
                env_vars["OPENOPS_MODEL_PROVIDER"] = llm_provider
                env_vars["OPENOPS_MODEL_NAME"] = model_name
                env_vars[env_var_names[llm_provider]] = api_key

    if env_vars:
        _write_env_file(env_vars)

    config = get_config()
    config.ensure_data_dir()

    _show_summary(env_vars)


__all__ = ["init_cmd"]
